name: CI

on:
  push:
    branches: [main]
  pull_request:

env:
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
  APP_PORT: 3000
  POSTGRES_PORT: 5432
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Short commit
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm ci

      - name: Lint with ESLint
        run: npx eslint . --max-warnings 0

      - name: Check formatting with Prettier
        run: npx prettier --check .

      - name: Run tests with Jest
        run: npm run devtest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker compose build
        env:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          IMAGE_TAG: ${{ env.IMAGE_TAG }}

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
          sudo mv ./bin/trivy /usr/local/bin/trivy

      - name: Scan image with Trivy
        run: |
          trivy image \
            --exit-code 1 \
            --quiet \
            --skip-version-check \
            --ignore-unfixed \
            --severity HIGH,CRITICAL \
            --format json "${IMAGE_NAME}:${IMAGE_TAG}" |
          jq '.Results[] | select(.Vulnerabilities | length > 0)'

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_PASS }}

      - name: Push Docker image
        run: docker push "${IMAGE_NAME}:${IMAGE_TAG}"

      - name: Start containers
        run: |
          docker compose down || true
          docker compose up -d
